name: credit_fraud
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5
  - aom=3.6.0
  - asttokens=3.0.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.10.5
  - cairo=1.18.4
  - colorama=0.4.6
  - comm=0.2.3
  - contourpy=1.3.2
  - cycler=0.12.1
  - dav1d=1.2.1
  - debugpy=1.8.17
  - decorator=5.2.1
  - double-conversion=3.3.1
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - expat=2.7.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.60.1
  - freeglut=3.4.0
  - freetype=2.14.1
  - fribidi=1.0.10
  - graphite2=1.3.14
  - harfbuzz=10.2.0
  - icu=73.1
  - importlib-metadata=8.7.0
  - ipykernel=7.0.1
  - ipython=8.37.0
  - jedi=0.19.2
  - jpeg=9f
  - jupyter_client=8.6.3
  - jupyter_core=5.9.1
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20250127.0
  - libavif=1.1.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang13=21.1.3
  - libdeflate=1.22
  - libevent=2.1.12
  - libexpat=2.7.1
  - libffi=3.4.4
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgomp=15.2.0
  - libhwloc=2.12.1
  - libiconv=1.18
  - libintl=0.22.5
  - libjpeg-turbo=2.0.0
  - libkrb5=1.21.3
  - liblapack=3.9.0
  - libpng=1.6.50
  - libpq=17.4
  - libre2-11=2024.07.02
  - libsodium=1.0.20
  - libsqlite=3.50.4
  - libtiff=4.7.0
  - libwebp-base=1.6.0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca
  - libxcb=1.17.0
  - libxml2=2.13.8
  - libxslt=1.1.43
  - libzlib=1.3.1
  - llvm-openmp=21.1.3
  - matplotlib=3.10.7
  - matplotlib-base=3.10.7
  - matplotlib-inline=0.1.7
  - mkl=2024.2.2
  - munkres=1.1.4
  - mysql-common=9.3.0
  - mysql-libs=9.3.0
  - nest-asyncio=1.6.0
  - numpy=2.2.6
  - openjpeg=2.5.3
  - openssl=3.5.4
  - packaging=25.0
  - pandas=2.3.3
  - parso=0.8.5
  - patsy=1.0.1
  - pickleshare=0.7.5
  - pillow=11.3.0
  - pip=25.2
  - pixman=0.46.4
  - platformdirs=4.5.0
  - prompt-toolkit=3.0.52
  - psutil=7.1.0
  - pthread-stubs=0.4
  - pure_eval=0.2.3
  - pygments=2.19.2
  - pyparsing=3.2.5
  - pyside6=6.9.2
  - python=3.10.18
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.10
  - pytz=2025.2
  - pywin32=311
  - pyzmq=27.1.0
  - qhull=2020.2
  - qtbase=6.9.2
  - qtdeclarative=6.9.2
  - qtshadertools=6.9.2
  - qtsvg=6.9.2
  - qttools=6.9.2
  - qtwebchannel=6.9.2
  - qtwebengine=6.9.2
  - qtwebsockets=6.9.2
  - re2=2024.07.02
  - scipy=1.15.2
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setuptools=80.9.0
  - six=1.17.0
  - snappy=1.2.1
  - sqlite=3.50.2
  - stack_data=0.6.3
  - statsmodels=0.14.5
  - tbb=2021.13.0
  - tk=8.6.15
  - tornado=6.5.2
  - traitlets=5.14.3
  - typing_extensions=4.15.0
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - unicodedata2=16.0.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wcwidth=0.2.14
  - wheel=0.45.1
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xz=5.6.4
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - altair==5.5.0
      - annotated-doc==0.0.3
      - annotated-types==0.7.0
      - anyio==4.11.0
      - attrs==25.4.0
      - fastapi==0.120.0
      - idna==3.11
      - imbalanced-learn==0.14.0
      - jinja2==3.1.6
      - joblib==1.5.2
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - lightgbm==4.6.0
      - llvmlite==0.45.1
      - markupsafe==3.0.3
      - narwhals==2.8.0
      - numba==0.62.1
      - prince==0.16.1
      - pydantic==2.12.3
      - pydantic-core==2.41.4
      - pynndescent==0.5.13
      - referencing==0.37.0
      - rpds-py==0.27.1
      - scikit-learn==1.7.2
      - sniffio==1.3.1
      - starlette==0.48.0
      - threadpoolctl==3.6.0
      - tqdm==4.67.1
      - typing-inspection==0.4.2
      - umap==0.1.1
      - umap-learn==0.5.9.post2
      - xgboost==3.1.0
prefix: C:\Users\isaac\anaconda3\envs\credit_fraud
